/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.JOptionPane;
import Project.*;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author ammaar
 */
public class customerCheckOut extends javax.swing.JFrame {

    /**
     * Creates new form customerCheckOut
     */
    public customerCheckOut() {
        initComponents();
        
        //////Set CheckOut Text Boxes Not Editable**********
        txtChOutCustomerName.setEditable(false);
        txtChOutCheckInDate.setEditable(false);
        txtChOutCheckOutDate.setEditable(false);
        txtChOutCustomerMobileNo.setEditable(false);
        txtChOutPricePerDay.setEditable(false);
        txtChOutNoOfDays.setEditable(false);
        txtChOutTotalBillAmount.setEditable(false);
        txtChOutCustomerEmail.setEditable(false);
       
    
    }
    
    int id=0;
    String Query;
    String roomType;
    String bed;
    String roomNo;
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtChOutRoomNo = new javax.swing.JTextField();
        btnChOutSearch = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtChOutCustomerName = new javax.swing.JTextField();
        txtChOutCheckInDate = new javax.swing.JTextField();
        txtChOutCheckOutDate = new javax.swing.JTextField();
        txtChOutCustomerMobileNo = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtChOutPricePerDay = new javax.swing.JTextField();
        txtChOutNoOfDays = new javax.swing.JTextField();
        txtChOutTotalBillAmount = new javax.swing.JTextField();
        txtChOutCustomerEmail = new javax.swing.JTextField();
        btnCkeckOut = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(60, 0));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CUSTOMER CHECK OUT ");

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 102));
        jLabel19.setText("Enter Room No");

        btnChOutSearch.setBackground(new java.awt.Color(0, 0, 102));
        btnChOutSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnChOutSearch.setText("Search");
        btnChOutSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChOutSearchActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 102));
        jLabel20.setText("Customer Name");

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 102));
        jLabel21.setText("Check IN Date");

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 102));
        jLabel22.setText("Check Out Date");

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 102));
        jLabel23.setText("Customer Mobile No");

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 102));
        jLabel24.setText("Price Per Day");

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 102));
        jLabel25.setText("No of Days Stayed");

        jLabel26.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 102));
        jLabel26.setText("Total Bill Amount");

        jLabel27.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 102));
        jLabel27.setText("Email");

        btnCkeckOut.setBackground(new java.awt.Color(0, 0, 102));
        btnCkeckOut.setForeground(new java.awt.Color(255, 255, 255));
        btnCkeckOut.setText("Check Out");
        btnCkeckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCkeckOutActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 102));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mobile No", "Address", "Gender", "Email", "ID Proof", "Check In Date", "Room No", "Bed", "Room Type", "Price Per Day"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1328, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChOutRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnChOutSearch))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtChOutCustomerName)
                            .addComponent(txtChOutCheckInDate)
                            .addComponent(txtChOutCheckOutDate)
                            .addComponent(txtChOutCustomerMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCkeckOut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addComponent(txtChOutPricePerDay)
                            .addComponent(txtChOutNoOfDays)
                            .addComponent(txtChOutTotalBillAmount)
                            .addComponent(txtChOutCustomerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtChOutRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChOutSearch))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtChOutCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(txtChOutPricePerDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtChOutCheckInDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(txtChOutNoOfDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtChOutCheckOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(txtChOutTotalBillAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtChOutCustomerMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(txtChOutCustomerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCkeckOut)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new hotelManagement().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCkeckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCkeckOutActionPerformed
        // TODO add your handling code here:
        String name=txtChOutCustomerName.getText();
        String mobileNumber=txtChOutCustomerMobileNo.getText();
        String email=txtChOutCustomerEmail.getText();
        
        String checkOut=txtChOutCheckOutDate.getText();
        String numberOfDaysStay=txtChOutNoOfDays.getText();
        String totalAmount=txtChOutTotalBillAmount.getText();
        
        roomNo=txtChOutRoomNo.getText();
        
        ///set values for last 3 colums*************
        Query="update hotel_customer set numberOfDaysStay='"+numberOfDaysStay+"', totalAmount='"+totalAmount+"', checkOut='"+checkOut+"' where id='"+id+"' ";
        InsertUpdateDelete.setData(Query, "");
        
        /// After CheckOut set Room Status to Not Booked***********************
        Query="update room set status='Not Booked' where roomNo='"+roomNo+"' ";
        InsertUpdateDelete.setData(Query, "");
        
        
        ///**************************************
        //// Print Bill Details as a PDF*********
        String path="D:\\SLIIT\\YEAR 02\\SEMESTER 02\\PPA\\PROJECT\\hotelCheckOut\\";
        com.itextpdf.text.Document doc=new com.itextpdf.text.Document();
        
        try{
            PdfWriter.getInstance(doc, new FileOutputStream(path+""+id+".pdf"));
            doc.open();
            Paragraph paragraph1=new Paragraph("                           KJ Hotel Manegement System \n");
            doc.add(paragraph1);
            
            Paragraph paragraph2=new Paragraph("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
            doc.add(paragraph2);
            
            Paragraph paragraph3=new Paragraph("\tBill ID: "+id+ "\nCustomer Details: \nName: "+name+"\nMobile Number: "+mobileNumber+"\nEmail: "+email+"\n");
            doc.add(paragraph3);
            doc.add(paragraph2);
            
            Paragraph paragraph4=new Paragraph("\tRoom Details: \nRoom No: "+txtChOutRoomNo.getText()+"\nRoom Type: "+roomType+"\nBed: "+bed+"\nPrice Per Day: "+txtChOutPricePerDay.getText()+" ");
            doc.add(paragraph4);
            doc.add(paragraph2);
            
            //// Create a Table and Insert it in to PDF *********
            PdfPTable tb1=new PdfPTable(4);
            tb1.addCell("Check In Date: "+txtChOutCheckInDate.getText());
            tb1.addCell("Check Out Date: "+checkOut);
            tb1.addCell("No Of Days Stayed: "+numberOfDaysStay);
            tb1.addCell("Total Bill Amount Payable: "+totalAmount);
            doc.add(tb1);
            doc.add(paragraph2);
            
            Paragraph paragraph5=new Paragraph("Thank You!!\nPlease Visit Again ");
            doc.add(paragraph5);
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();      
        
        /// want to open the pdf or not********
        int a=JOptionPane.showConfirmDialog(null, "Do you want to print the Bill?","Select",JOptionPane.YES_NO_OPTION);
        
        if(a==0){
            ///To open that Particular PDF********
            try{
                if((new File(path+id+".pdf")).exists()){
                    Process p=Runtime
                            .getRuntime()
                            .exec("rundll32 url.dll,FileProtocolHandler D:\\SLIIT\\YEAR 02\\SEMESTER 02\\PPA\\PROJECT\\hotelCheckOut\\"+id+".pdf");
            }else{
                    System.out.println("File Is Nor Exist!!");
                }
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
                    
        }
        
        
        ////To Send The Bill To The Customer Via Email********
       /***
        try {
            SendEmail X=new SendEmail();
            JOptionPane.showMessageDialog(rootPane, "Email sent successful \n"+ X.sendMail(txtChOutCustomerEmail.getText(), id));
        } catch (Exception ex) {
            Logger.getLogger(customerCheckOut.class.getName()).log(Level.SEVERE, null, ex);
        }
        **/
        
        
        setVisible(false);
        new customerCheckOut().setVisible(true);
        
    }//GEN-LAST:event_btnCkeckOutActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ////To Display All Customers in Table in Check Out Page********

        ResultSet rs=Select.getData("select * from hotel_customer where checkOut is NULL");
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        
        try{
            
            while(rs.next()){
                model.addRow(new Object[] {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9), rs.getString(10), rs.getString(11), rs.getString(12)});
            }
            rs.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void btnChOutSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChOutSearchActionPerformed
        // TODO add your handling code here:
        
        ///To search and automatically fill fields******
        String roomNo=txtChOutRoomNo.getText();
        
        try{
            ResultSet rs=Select.getData("select * from hotel_customer where roomNo='"+roomNo+"' and checkOut is NULL ");
            if(rs.next()){
                txtChOutRoomNo.setEditable(false);
                id=rs.getInt(1);
                txtChOutCustomerName.setText(rs.getString(2));
                txtChOutCheckInDate.setText(rs.getString(8));
                txtChOutCustomerMobileNo.setText(rs.getString(3));
                txtChOutPricePerDay.setText(rs.getString(12));
                
                ///To set the CheckOut Date *********
                SimpleDateFormat myFormat=new SimpleDateFormat("yyyy/MM/dd");
                Calendar cal=Calendar.getInstance();
                txtChOutCheckOutDate.setText(myFormat.format(cal.getTime()));
                
                ////To calculate No Of days Stayed  ********
                String dateBeforeString=rs.getString(8);
                java.util.Date dateBefore=myFormat.parse(dateBeforeString);         ///java util cannot be converted to java.Date*****
                
                String dateAfterString=myFormat.format(cal.getTime());
                java.util.Date dateAfter=myFormat.parse(dateAfterString);
                
                ///To get difference between Check In and Check Out date********
                long difference=dateAfter.getTime() - dateBefore.getTime();
                int noOfDayStay=(int) (difference/(1000*60*60*24));
                
                if(noOfDayStay==0){
                    noOfDayStay=1;
                }
                
                ///callculating Total bill Amount*******
                txtChOutNoOfDays.setText(String.valueOf(noOfDayStay));
                float price=Float.parseFloat(txtChOutPricePerDay.getText());
                txtChOutTotalBillAmount.setText(String.valueOf(noOfDayStay*price));
                txtChOutCustomerEmail.setText(rs.getString(6));
                
                roomType=rs.getString(11);
                bed=rs.getString(10);
                
            }else{
                JOptionPane.showMessageDialog(null, "Room No '"+roomNo+"' is not Booked or does not exist!!");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btnChOutSearchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new customerCheckOut().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerCheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChOutSearch;
    private javax.swing.JButton btnCkeckOut;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtChOutCheckInDate;
    private javax.swing.JTextField txtChOutCheckOutDate;
    private javax.swing.JTextField txtChOutCustomerEmail;
    private javax.swing.JTextField txtChOutCustomerMobileNo;
    private javax.swing.JTextField txtChOutCustomerName;
    private javax.swing.JTextField txtChOutNoOfDays;
    private javax.swing.JTextField txtChOutPricePerDay;
    private javax.swing.JTextField txtChOutRoomNo;
    private javax.swing.JTextField txtChOutTotalBillAmount;
    // End of variables declaration//GEN-END:variables
}
