package GUI;
import Code.Employee;
import GUI.salary;
import UI.home;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
///import org.apache.commons.dbutils.DbUtils;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pasan
 */
public class emp extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
   Employee employee ;
    
    public emp() {
        initComponents();
        Connect();
    }
  
Connection con;
PreparedStatement pst;

 public void Connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/ppakj_db?", "root","");
            
            
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    
    
    
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txthead = new javax.swing.JLabel();
        txtempID = new javax.swing.JTextField();
        txtempname = new javax.swing.JTextField();
        txt_nic = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_address = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jbutton_exit = new javax.swing.JButton();
        jButton_submit = new javax.swing.JButton();
        txt_age = new javax.swing.JTextField();
        txt_contact_number = new javax.swing.JTextField();
        txt_salary = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_address = new javax.swing.JTextArea();
        jButton_update = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        jButton_nect_page = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        txthead.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txthead.setText("Employee Management System");

        txtempID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtempIDActionPerformed(evt);
            }
        });

        txtempname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtempnameActionPerformed(evt);
            }
        });

        txt_nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nicActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel1.setText("Employee ID");

        jLabel2.setText("Full Name");

        jLabel3.setText("NIC");

        jLabel4.setText("Gender");

        txt_address.setText("Address");

        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Full Name", "NIC", "Gender", "Address", "Date of Birth", "Age", "Contact Number", "Salary"
            }
        ));
        jScrollPane1.setViewportView(jtable);

        jLabel6.setText("Date of Birth");

        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        jLabel7.setText("Age");

        jLabel8.setText("Contact Number");

        jLabel9.setText("Salary");

        jbutton_exit.setText("Close");
        jbutton_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_exitActionPerformed(evt);
            }
        });

        jButton_submit.setText("Add");
        jButton_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_submitActionPerformed(evt);
            }
        });

        txt_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ageActionPerformed(evt);
            }
        });

        txt_contact_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contact_numberActionPerformed(evt);
            }
        });

        jTextArea_address.setColumns(20);
        jTextArea_address.setRows(5);
        jScrollPane2.setViewportView(jTextArea_address);

        jButton_update.setText("Search");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });

        jButton_clear.setText("Clear Data");
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });

        jButton_nect_page.setText("Employee Salary Details System");
        jButton_nect_page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nect_pageActionPerformed(evt);
            }
        });

        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        print.setText("Print Report");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 153, 255));
        jButton5.setForeground(new java.awt.Color(0, 0, 102));
        jButton5.setText("Back to Main Menu");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(262, 262, 262)
                                .addComponent(txthead, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton_submit)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4)
                                            .addComponent(txt_address))
                                        .addGap(43, 43, 43)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(59, 59, 59)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jbutton_exit)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(updatebtn))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jButton_clear)
                                                        .addGap(40, 40, 40)
                                                        .addComponent(jButton_update))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtempID, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(263, 263, 263)
                                                .addComponent(jLabel3))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(136, 136, 136)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel9))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(txtempname, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(93, 93, 93)
                                                        .addComponent(txt_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(49, 49, 49)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel8)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                        .addComponent(txt_contact_number, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 365, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton_nect_page))
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(print)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthead, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtempID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtempname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_contact_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(txt_address))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_clear)
                            .addComponent(jButton_update))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_submit)
                            .addComponent(jbutton_exit)
                            .addComponent(updatebtn))))
                .addGap(42, 42, 42)
                .addComponent(jButton_nect_page)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(print)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtempnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempnameActionPerformed

    private void txtempIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempIDActionPerformed

    private void jbutton_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_exitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jbutton_exitActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
                  String EmpID=txtempID.getText();
           String sql2 = "Select `Emp_Name` from `employee` where `Emp_ID`='" + EmpID + "'";
           String result2="";
           String sql11="";
           PreparedStatement pst2;
        try {                                               
           // TODO Search details here:

           if(EmpID.equals("")){
               sql11 = "Select * from employee";
           }   
           else{
               sql11 = "Select * from employee where `Emp_ID`='" + EmpID + "'";
           }
           
           PreparedStatement pst11 = con.prepareStatement(sql11);
           ResultSet rs11 = pst11.executeQuery();
           jtable.setModel(DbUtils.resultSetToTableModel(rs11));
           
           try {
               pst2 = con.prepareStatement(sql2);
               
               ResultSet rs2 = pst2.executeQuery();
               
               if (rs2.next()) {
                   result2 = rs2.getString(1);
                   txtempname.setText(result2);
               }
           } catch (SQLException ex) {
               Logger.getLogger(emp.class.getName()).log(Level.SEVERE, null, ex);
           }
           
           String sql3 = "Select `NIC` from `employee` where `Emp_ID`='" + EmpID + "'";
           String result3="";
           PreparedStatement pst3;
           try {
               pst3= con.prepareStatement(sql3);
               
               ResultSet rs3 = pst3.executeQuery();
               
               if (rs3.next()) {
                   result3 = rs3.getString(1);
                   txt_nic.setText(result3);
               }
           } catch (SQLException ex) {
               Logger.getLogger(emp.class.getName()).log(Level.SEVERE, null, ex);
           }
           
           
           
           String sql4 = "Select `Gender` from `employee` where `Emp_ID`='" + EmpID + "'";
           String result4="";
           PreparedStatement pst4;
           try {
               pst4= con.prepareStatement(sql4);
               
               ResultSet rs4 = pst4.executeQuery();
               
               if (rs4.next()) {
                   result4 = rs4.getString(1);
                   jComboBox1.setSelectedItem(result4);
               }
           } catch (SQLException ex) {
               Logger.getLogger(emp.class.getName()).log(Level.SEVERE, null, ex);
           }
           
           
           
           String sql5 = "Select `Address` from `employee` where `Emp_ID`='" + EmpID + "'";
           String result5="";
           PreparedStatement pst5;
           try {
               pst5= con.prepareStatement(sql5);
               
               ResultSet rs5 = pst5.executeQuery();
               
               if (rs5.next()) {
                   result5 = rs5.getString(1);
                   jTextArea_address.setText(result5);
               }
           } catch (SQLException ex) {
               Logger.getLogger(emp.class.getName()).log(Level.SEVERE, null, ex);
           }
           
           
           
           
           String sql6 = "Select `Date_Of_Birth` from `employee` where `Emp_ID`='" + EmpID + "'";
           String result6="";
           PreparedStatement pst6;
           try {
               pst6= con.prepareStatement(sql6);
               
               ResultSet rs6 = pst6.executeQuery();
               
               if (rs6.next()) {
                   result6 = rs6.getString(1);
                   Date date=new SimpleDateFormat("dd-mm-yy").parse(result6);
                   jDateChooser1.setDate(date);
               }
           } catch (SQLException ex) {
               Logger.getLogger(emp.class.getName()).log(Level.SEVERE, null, ex);
           } catch (ParseException ex) {
               Logger.getLogger(emp.class.getName()).log(Level.SEVERE, null, ex);
           }
           
           
           
           String sql7 = "Select `Age` from `employee` where `Emp_ID`='" + EmpID + "'";
           String result7="";
           PreparedStatement pst7;
           try {
               pst7= con.prepareStatement(sql7);
               
               ResultSet rs7 = pst7.executeQuery();
               
               if (rs7.next()) {
                   result7 = rs7.getString(1);
                   txt_age.setText(result7);
               }
           } catch (SQLException ex) {
               Logger.getLogger(emp.class.getName()).log(Level.SEVERE, null, ex);
           }
           
           
           
           String sql8 = "Select `Contact_Number` from `employee` where `Emp_ID`='" + EmpID + "'";
           String result8="";
           PreparedStatement pst8;
           try {
               pst8= con.prepareStatement(sql8);
               
               ResultSet rs8 = pst8.executeQuery();
               
               if (rs8.next()) {
                   result8 = rs8.getString(1);
                   txt_contact_number.setText(result7);
               }
           } catch (SQLException ex) {
               Logger.getLogger(emp.class.getName()).log(Level.SEVERE, null, ex);
           }
           
           
           
           
           String sql9 = "Select `Salary` from `employee` where `Emp_ID`='" + EmpID + "'";
           String result9="";
           PreparedStatement pst9;
           try {
               pst9= con.prepareStatement(sql9);
               
               ResultSet rs9 = pst9.executeQuery();
               
               if (rs9.next()) {
                   result9 = rs9.getString(1);
                   txt_salary.setText(result9);
               }
           } catch (SQLException ex) {
               Logger.getLogger(emp.class.getName()).log(Level.SEVERE, null, ex);
           }
           
           
           
           
           
           
           
           
       } catch (SQLException ex) {
           Logger.getLogger(emp.class.getName()).log(Level.SEVERE, null, ex);
       }








    }//GEN-LAST:event_jButton_updateActionPerformed

    private void txt_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ageActionPerformed

    private void jButton_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_submitActionPerformed
        // TODO Enter :
        if(!"".equals(txt_contact_number.getText())){
            int no=txt_contact_number.getText().length();
            if(no==10){
                
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect Contact Number,should be 10 digits");
            }
        }
        if(!"".equals(txtempID.getText())){
            if(txtempID.getText().length()>=3){
                
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect ID,should be 3 digits or more");
            }
        }
        if(!"".equals(txt_nic.getText())){
            if((txt_nic.getText().matches("^\\d{12}")||txt_nic.getText().matches("^\\d{9}[V]"))){
                
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect NIC Number,should be 12 digits or 9 digits ended by 'V'");
            }
        }
        if(!"".equals(txtempID.getText()) && !"".equals(txtempname.getText())&& !"".equals(txt_nic.getText())&& !"".equals(jTextArea_address.getText())&& !"".equals(txt_age.getText())&& !"".equals(txt_contact_number.getText())&& !"".equals(txt_salary.getText())&&txtempID.getText().length()>=3&&(txt_nic.getText().matches("^\\d{12}")||txt_nic.getText().matches("^\\d{9}[V]")))
            {
        try {
            
            String Employee_ID=txtempID.getText();
            String Employee_Name=txtempname.getText();
            String NIC=txt_nic.getText();
            String Gender=(String) jComboBox1.getSelectedItem();
            String Address=jTextArea_address.getText();
            java.sql.Date sqldate = new java.sql.Date(jDateChooser1.getDate().getTime());
            String Date_of_Birth=sqldate.toString();
            String Age=txt_age.getText();
            String contact_number=txt_contact_number.getText();
            String salary=txt_salary.getText();
            
             
            pst=con.prepareStatement("insert into employee(Emp_ID,Emp_Name,NIC,Gender,Address,Date_Of_Birth,Age,Contact_Number,Salary)values(?,?,?,?,?,?,?,?,?)");
            pst.setString(1,Employee_ID);
            pst.setString(2, Employee_Name);
            pst.setString(3, NIC);
            pst.setString(4,Gender);
            pst.setString(5,Address);
            pst.setString(6,Date_of_Birth);
            pst.setString(7,Age);
            pst.setString(8,contact_number);
            pst.setString(9,salary);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "EMP added");
            
            
           txtempID.setText("");
           txtempname.setText("");
           txt_nic.setText("");
           jTextArea_address.setText("");
           jDateChooser1.setDate(null);
           txt_age.setText("");
           txt_contact_number.setText("");
           jComboBox1.setSelectedItem("");
           txt_salary.setText("");
            
            String sql1 = "Select * from employee";
            PreparedStatement pst1 = con.prepareStatement(sql1);
            ResultSet rs = pst1.executeQuery();
            jtable.setModel(DbUtils.resultSetToTableModel(rs));

            {

            }

        }  catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else
        {
              JOptionPane.showMessageDialog(this, "Some values are left blank,please enter all");  
                }

    }//GEN-LAST:event_jButton_submitActionPerformed

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
        // TODO Clear code here:
        
             txtempID.setText("");
           txtempname.setText("");
           txt_nic.setText("");
           jTextArea_address.setText("");
           jDateChooser1.setDate(null);
           txt_age.setText("");
           txt_contact_number.setText("");
           jComboBox1.setSelectedItem("");
           txt_salary.setText("");
   
    }//GEN-LAST:event_jButton_clearActionPerformed

    private void jButton_nect_pageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nect_pageActionPerformed
        // TODO next page here:
        salary v=new salary();
            v.setVisible(true);
    }//GEN-LAST:event_jButton_nect_pageActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
       try {
           // TODO Update here:
           String EmpID=txtempID.getText();
           java.sql.Date sqldate = new java.sql.Date(jDateChooser1.getDate().getTime());
           String sqlupdate="UPDATE `employee` SET `Emp_ID`='"+txtempID.getText()+"',`Emp_Name`='" + txtempname.getText() + "',`NIC`='" + txt_nic.getText() + "',`Gender`='" + jComboBox1.getSelectedItem() + "',`Address`='" + jTextArea_address.getText() + "',`Date_Of_Birth`='" + sqldate + "',`Age`='"+txt_age.getText()+"',`Contact_Number`='" + txt_contact_number.getText() + "',`Salary`='"+txt_salary.getText()+"' WHERE `Emp_ID`='" + EmpID + "'";
           PreparedStatement pstmt = con.prepareStatement(sqlupdate);
           pstmt.executeUpdate();
           
           String sql1 = "Select * from employee";
            PreparedStatement pst1 = con.prepareStatement(sql1);
            ResultSet rs = pst1.executeQuery();
            jtable.setModel(DbUtils.resultSetToTableModel(rs));
       } catch (SQLException ex) {
           Logger.getLogger(emp.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void txt_nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nicActionPerformed

    private void txt_contact_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contact_numberActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_contact_numberActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
         JasperDesign jdesign;
        try {
            jdesign = JRXmlLoader.load("D:\\SLIIT\\YEAR 02\\SEMESTER 02\\PPA\\PROJECT\\KJEnterprises\\src\\main\\java\\GUI\\empreport1.jrxml");
            String query="select * from employee";
        
        JRDesignQuery updateQuery=new JRDesignQuery();
        updateQuery.setText(query);
        
        jdesign.setQuery(updateQuery);
        
        JasperReport jreport=JasperCompileManager.compileReport(jdesign);
        JasperPrint jprint=JasperFillManager.fillReport(jreport,null,con);
        
        JasperViewer.viewReport(jprint);
        
        
        } catch (JRException ex) {
            Logger.getLogger(emp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_nect_page;
    private javax.swing.JButton jButton_submit;
    private javax.swing.JButton jButton_update;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_address;
    private javax.swing.JButton jbutton_exit;
    private javax.swing.JTable jtable;
    private javax.swing.JButton print;
    private javax.swing.JLabel txt_address;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_contact_number;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txtempID;
    private javax.swing.JTextField txtempname;
    private javax.swing.JLabel txthead;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
