/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory;


import UI.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author User
 * 
 */

public class Stock extends javax.swing.JFrame {

    private java.sql.Date sqldate;

    /**
     * Creates new form Main
     */
    public Stock() {
        initComponents();
        Connect();
        load();
        dateTime();
    }
    
    
    Connection con;
    PreparedStatement pst;
    DefaultTableModel df;
    
    
    
    
    
    public void Connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/ppakj_db?", "root","");
            
            
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
     public void load()
    {
        int a;
        try {
            pst=con.prepareStatement("select * from inventory");
            ResultSet rs=pst.executeQuery();
            
            ResultSetMetaData rd=rs.getMetaData();
            a = rd.getColumnCount();
            df=(DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2= new Vector();
                for(int i=1;i<=a;i++)
                {
                    v2.add(rs.getString("id"));
                    v2.add(rs.getString("pname"));
                    v2.add(rs.getString("description"));
                    v2.add(rs.getString("quantity"));
                    v2.add(rs.getString("date"));
                    v2.add(rs.getString("level"));
                
                }
                df.addRow(v2);
            
            
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
     public void dateTime(){
     
         DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd   HH:mm");
         LocalDateTime now=LocalDateTime.now();
         dateTime.setText(dtf.format(now));
            
   
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SupButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        txtPname = new javax.swing.JTextField();
        txtDes = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLevel = new javax.swing.JTextField();
        AddButton2 = new javax.swing.JButton();
        EditButton2 = new javax.swing.JButton();
        deletebutton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        Updatebutton = new javax.swing.JButton();
        txtQty = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        ReportButton = new javax.swing.JButton();
        dateTime = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("Stock  Managemenet System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 10, 364, -1));

        SupButton.setBackground(new java.awt.Color(0, 0, 0));
        SupButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        SupButton.setForeground(new java.awt.Color(255, 255, 255));
        SupButton.setText("Manage Suppliers");
        SupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 11, 199, 42));

        jLabel2.setText("Item Code");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 100, -1, -1));

        jLabel3.setText("Product Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 150, -1, -1));

        jLabel4.setText("Description");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 100, -1, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 133, 31, -1));

        txtCode.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                txtCodeMouseWheelMoved(evt);
            }
        });
        txtCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodeKeyPressed(evt);
            }
        });
        getContentPane().add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 119, 149, -1));

        txtPname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtPname, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 169, 149, -1));

        txtDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDesActionPerformed(evt);
            }
        });
        getContentPane().add(txtDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 158, 65));

        jLabel7.setText("Re Order Level");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 152, -1, -1));

        txtLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLevelActionPerformed(evt);
            }
        });
        getContentPane().add(txtLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 171, 147, -1));

        AddButton2.setBackground(new java.awt.Color(0, 0, 255));
        AddButton2.setText("Add");
        AddButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(AddButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 210, 63, -1));

        EditButton2.setBackground(new java.awt.Color(255, 255, 102));
        EditButton2.setText("Edit");
        EditButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(EditButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 210, 67, -1));

        deletebutton2.setBackground(new java.awt.Color(255, 102, 102));
        deletebutton2.setText("Delete");
        deletebutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebutton2ActionPerformed(evt);
            }
        });
        getContentPane().add(deletebutton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 210, 71, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 210, 66, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Product Name", "Description", "Quantity", "Last Modified", "ReOrder Level"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 241, 915, 402));

        jLabel8.setText("Last Modified");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 73, 20));

        txtDate.setEditable(false);
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 119, 147, -1));

        Updatebutton.setBackground(new java.awt.Color(153, 153, 153));
        Updatebutton.setText("Update Quantity");
        Updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Updatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 210, -1, -1));

        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtyKeyPressed(evt);
            }
        });
        getContentPane().add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 119, 137, -1));

        jLabel6.setText("Quantity");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 100, -1, -1));

        searchButton.setBackground(new java.awt.Color(204, 255, 255));
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(919, 63, -1, -1));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 64, 297, -1));

        ReportButton.setBackground(new java.awt.Color(0, 255, 0));
        ReportButton.setText("Report");
        ReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ReportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(931, 661, -1, -1));

        dateTime.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        getContentPane().add(dateTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 180, 26));

        jButton5.setBackground(new java.awt.Color(153, 153, 255));
        jButton5.setForeground(new java.awt.Color(0, 0, 102));
        jButton5.setText("Back to Main Menu");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupButtonActionPerformed
        
            Supplier v=new Supplier();
            v.setVisible(true);
    }//GEN-LAST:event_SupButtonActionPerformed

    private void txtLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLevelActionPerformed

    private void txtPnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPnameActionPerformed

    private void txtDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDesActionPerformed

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    private void EditButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButton2ActionPerformed
        // TODO add your handling code here:
        df=(DefaultTableModel)jTable1.getModel();
        
        int selected=jTable1.getSelectedRow();
        
        
        int id=Integer.parseInt(df.getValueAt(selected, 0).toString());
        
            String code=txtCode.getText();
            String pname=txtPname.getText();
            String desc=txtDes.getText();
            String quantity=txtQty.getText();
            String level=txtLevel.getText();
            
             
        try {
             Date date=new Date();
            java.sql.Date sqldate=new java.sql.Date(date.getTime());
            
            pst=con.prepareStatement("update inventory set id=?,pname=?,description=?,quantity=?,date=?,level=? where id=?");
            
            pst.setString(1,code);
            pst.setString(2,pname);
            pst.setString(3,desc);
            pst.setString(4,quantity);
            pst.setDate(5,sqldate);
            pst.setString(6,level);
            pst.setInt(7,id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Item Updated");
            
            
            txtCode.setText("");
            txtPname.setText("");
            txtDes.setText("");
            txtQty.setText("");
            txtDate.setText("");
            txtLevel.setText("");
            txtCode.requestFocus();
            load();
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            
        
        
  
    }//GEN-LAST:event_EditButton2ActionPerformed

    private void deletebutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebutton2ActionPerformed
        // TODO add your handling code here:
        df=(DefaultTableModel)jTable1.getModel();
        
        int selected=jTable1.getSelectedRow();
        
        int id=Integer.parseInt(df.getValueAt(selected, 0).toString());
        
        try {
            pst=con.prepareStatement("delete from inventory where id=?");
            pst.setInt(1,id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Item Deleted");
            
            
            txtCode.setText("");
            txtPname.setText("");
            txtDes.setText("");
            txtQty.setText("");
            txtDate.setText("");
            txtLevel.setText("");
            txtCode.requestFocus();
            load();
            
            AddButton2.setEnabled(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deletebutton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            txtCode.setText("");
            txtPname.setText("");
            txtDes.setText("");
            txtQty.setText("");
            txtLevel.setText("");
            txtDate.setText("");
            
            txtCode.requestFocus();
            
            AddButton2.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void AddButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButton2ActionPerformed
     if(txtCode.getText().isEmpty()){
         JOptionPane.showMessageDialog(this, "Item Code is required!");
     }
     if(txtPname.getText().isEmpty()){
         JOptionPane.showMessageDialog(this, "Product Name is required!");
     }
     if(txtDes.getText().isEmpty()){
         JOptionPane.showMessageDialog(this, "Description is required!");
     }
     if(txtQty.getText().isEmpty()){
         JOptionPane.showMessageDialog(this, "Quantity is required!");
     }
     if(txtLevel.getText().isEmpty()){
         JOptionPane.showMessageDialog(this, "ReOrder Level is required!");
     }
        try {
            String code=txtCode.getText();
            String pname=txtPname.getText();
            String desc=txtDes.getText();
            String quantity=txtQty.getText();
            String level=txtLevel.getText();
            
            Date date=new Date();
            java.sql.Date sqldate=new java.sql.Date(date.getTime());
            pst=con.prepareStatement("insert into inventory(id,pname,description,quantity,date,level)values(?,?,?,?,?,?)");
            pst.setString(1,code);
            pst.setString(2,pname);
            pst.setString(3,desc);
            pst.setString(4,quantity);
            pst.setDate(5,sqldate);
            pst.setString(6,level);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Item Added");
            
            
            txtCode.setText("");
            txtPname.setText("");
            txtDes.setText("");
            txtQty.setText("");
            txtLevel.setText("");
            txtCode.requestFocus();
            load();
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        df=(DefaultTableModel)jTable1.getModel();
        
        int selected=jTable1.getSelectedRow();
        
        int id=Integer.parseInt(df.getValueAt(selected, 0).toString());
         txtCode.setText(df.getValueAt(selected, 0).toString());
        txtPname.setText(df.getValueAt(selected, 1).toString());
        txtDes.setText(df.getValueAt(selected, 2).toString());
        txtQty.setText(df.getValueAt(selected, 3).toString());
        txtDate.setText(df.getValueAt(selected, 4).toString());
        txtLevel.setText(df.getValueAt(selected, 5).toString());
         
        
        AddButton2.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void UpdatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebuttonActionPerformed

        try {
            
            String stn = txtPname.getText();
            String stq = txtQty.getText();
            String code=txtCode.getText();
            String date=txtDate.getText();
            
            
            int sal=0;

            
            String sql1 = "Select `quantity` from `inventory` where `id`='" + code + "'";
            PreparedStatement pstmt1 = con.prepareStatement(sql1);
            ResultSet rs1 = pstmt1.executeQuery();
            if (rs1.next()) {
                sal = rs1.getInt(1);

            }
            
            sal=sal+Integer.parseInt(stq);
            String sql = "Update inventory set quantity='" + sal + "' where id='" + code + "'";

            PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Quantity Updated");
           
            load();
            
        } catch (SQLException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_UpdatebuttonActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtDateActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        try {
            String sql="select * from inventory where pname=?";
            pst= con.prepareStatement(sql);
            pst.setString(1,txtSearch.getText());
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                
                txtPname.setText(rs.getString("pname"));
                txtCode.setText(rs.getString("id"));
                txtDes.setText(rs.getString("description"));
                txtQty.setText(rs.getString("quantity"));
                txtDate.setText(rs.getString("date"));
                txtLevel.setText(rs.getString("level"));
            
            
            
            
            
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeKeyPressed
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(Character.isLetter(c)){
           JOptionPane.showMessageDialog(this, "Enter Only Numeric Value!");
        
        }
        
    }//GEN-LAST:event_txtCodeKeyPressed

    private void txtQtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyPressed
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(Character.isLetter(c)){
           JOptionPane.showMessageDialog(this, "Enter Only Numeric Value!");
        
        }
    }//GEN-LAST:event_txtQtyKeyPressed

    private void txtCodeMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_txtCodeMouseWheelMoved
       // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeMouseWheelMoved

    private void ReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportButtonActionPerformed
        // TODO add your handling code here:
        JasperDesign jdesign;
        try {
            jdesign = JRXmlLoader.load("D:\\SLIIT\\YEAR 02\\SEMESTER 02\\PPA\\PROJECT\\KJEnterprises\\src\\main\\java\\Inventory\\Stockreport1.jrxml");
            String query="select * from inventory";
        
        JRDesignQuery updateQuery=new JRDesignQuery();
        updateQuery.setText(query);
        
        jdesign.setQuery(updateQuery);
        
        JasperReport jreport=JasperCompileManager.compileReport(jdesign);
        JasperPrint jprint=JasperFillManager.fillReport(jreport,null,con);
        
        JasperViewer.viewReport(jprint);
        
        
        } catch (JRException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_ReportButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Stock().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton2;
    private javax.swing.JButton EditButton2;
    private javax.swing.JButton ReportButton;
    private javax.swing.JButton SupButton;
    private javax.swing.JButton Updatebutton;
    private javax.swing.JLabel dateTime;
    private javax.swing.JButton deletebutton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDes;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtPname;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

}