/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public final class Supplier extends javax.swing.JFrame {

    /**
     * Creates new form Supplier
     */
    public Supplier() {
        initComponents();
        Connect(); 
        load();
        dateTime();
    }
    Connection con;
    PreparedStatement pst;
    DefaultTableModel df;
    
    
    
    
    public void Connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/ppakj_db?", "root","");
            
            
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    
    
    
}
    
    
    public void load()
    {
        int a;
        try {
            pst=con.prepareStatement("select * from supplier");
            ResultSet rs=pst.executeQuery();
            
            ResultSetMetaData rd=rs.getMetaData();
            a = rd.getColumnCount();
            df=(DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2= new Vector();
                for(int i=1;i<=a;i++)
                {
                    v2.add(rs.getString("id"));
                    v2.add(rs.getString("name"));
                    v2.add(rs.getString("phone"));
                    v2.add(rs.getString("email"));
                    v2.add(rs.getString("product"));
                
                }
                df.addRow(v2);
            
            
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    
    }
    public void dateTime(){
     
         DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd   HH:mm");
         LocalDateTime now=LocalDateTime.now();
         dateTime1.setText(dtf.format(now));
            
   
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSupName = new javax.swing.JTextField();
        txtSupNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSupProduct = new javax.swing.JTextField();
        elab = new javax.swing.JLabel();
        plab = new javax.swing.JLabel();
        EditButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ClearButton = new javax.swing.JButton();
        CloseButton = new javax.swing.JButton();
        SearchButton1 = new javax.swing.JButton();
        txtSearch1 = new javax.swing.JTextField();
        ReportButton2 = new javax.swing.JButton();
        dateTime1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel1.setText("Supplier Management");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 11, -1, 51));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Supplier Details");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Phone No:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Email:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Product:");

        txtSupNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSupNoFocusLost(evt);
            }
        });
        txtSupNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupNoActionPerformed(evt);
            }
        });
        txtSupNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupNoKeyPressed(evt);
            }
        });

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        elab.setFont(new java.awt.Font("Times New Roman", 2, 10)); // NOI18N
        elab.setForeground(new java.awt.Color(255, 0, 0));

        plab.setFont(new java.awt.Font("Times New Roman", 2, 10)); // NOI18N
        plab.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(elab, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtSupName, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtSupNo, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                        .addComponent(txtSupProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                        .addComponent(plab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3))
                    .addComponent(txtSupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSupNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(plab, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(elab, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSupProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 132, -1, -1));

        EditButton.setBackground(new java.awt.Color(255, 255, 102));
        EditButton.setText("Edit");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 544, 91, 44));

        DeleteButton.setBackground(new java.awt.Color(255, 102, 102));
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 544, 91, 44));

        AddButton.setBackground(new java.awt.Color(0, 0, 204));
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 544, 91, 44));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier ID", "Supplier Name", "Phone Number", "Email", "Product"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 610, 374));

        ClearButton.setBackground(new java.awt.Color(255, 255, 255));
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 544, 91, 44));

        CloseButton.setBackground(new java.awt.Color(204, 0, 0));
        CloseButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        CloseButton.setText("Close");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 30, -1, -1));

        SearchButton1.setBackground(new java.awt.Color(204, 255, 255));
        SearchButton1.setText("Search");
        SearchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(SearchButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(829, 100, -1, -1));

        txtSearch1.setToolTipText("");
        txtSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearch1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 101, 205, -1));

        ReportButton2.setBackground(new java.awt.Color(153, 255, 153));
        ReportButton2.setText("Report");
        ReportButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(ReportButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 544, 85, 44));

        dateTime1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        getContentPane().add(dateTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 137, 22));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        
        df=(DefaultTableModel)jTable1.getModel();
        
        int selected=jTable1.getSelectedRow();
        
        int id=Integer.parseInt(df.getValueAt(selected, 0).toString());
        
            String vname=txtSupName.getText();
            String phone=txtSupNo.getText();
            String email=txtEmail.getText();
            String product=txtSupProduct.getText();
            
             
        try {
            pst=con.prepareStatement("update supplier set name=?,phone=?,email=?,product=? where id=?");
            pst.setString(1,vname);
            pst.setString(2,phone);
            pst.setString(3,email);
            pst.setString(4,product);
            pst.setInt(5,id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Supplier Updated");
            
            
            txtSupName.setText("");
            txtSupNo.setText("");
            txtEmail.setText("");
            txtSupProduct.setText("");
            txtSupName.requestFocus();
            load();
            AddButton.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
        
    }//GEN-LAST:event_EditButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        
        df=(DefaultTableModel)jTable1.getModel();
        
        int selected=jTable1.getSelectedRow();
        
        int id=Integer.parseInt(df.getValueAt(selected, 0).toString());
        
            
             
        try {
            pst=con.prepareStatement("delete from supplier where id=?");
            pst.setInt(1,id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Supplier Deleted");
            
            
            txtSupName.setText("");
            txtSupNo.setText("");
            txtEmail.setText("");
            txtSupProduct.setText("");
            txtSupName.requestFocus();
            load();
            AddButton.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
    if(txtSupName.getText().isEmpty()){
         JOptionPane.showMessageDialog(this, "Supplier Name is required!");
     }
     if(txtSupNo.getText().isEmpty()){
         JOptionPane.showMessageDialog(this, "Phone Number is required!");
     }
     if(txtEmail.getText().isEmpty()){
         JOptionPane.showMessageDialog(this, "Email is required!");
     }
     if(txtSupProduct.getText().isEmpty()){
         JOptionPane.showMessageDialog(this, "Product Type is required!");
     }    

        try {
            String vname=txtSupName.getText();
            String phone=txtSupNo.getText();
            String email=txtEmail.getText();
            String product=txtSupProduct.getText();
            
             
            pst=con.prepareStatement("insert into supplier(name,phone,email,product)values(?,?,?,?)");
            pst.setString(1,vname);
            pst.setString(2,phone);
            pst.setString(3,email);
            pst.setString(4,product);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Supplier Added");
            
            
            txtSupName.setText("");
            txtSupNo.setText("");
            txtEmail.setText("");
            txtSupProduct.setText("");
            txtSupName.requestFocus();
            load();
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void txtSupNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupNoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        df=(DefaultTableModel)jTable1.getModel();
        
        int selected=jTable1.getSelectedRow();
        
        int id=Integer.parseInt(df.getValueAt(selected, 0).toString());
        txtSupName.setText(df.getValueAt(selected, 1).toString());
        txtSupNo.setText(df.getValueAt(selected, 2).toString());
        txtEmail.setText(df.getValueAt(selected, 3).toString());
        txtSupProduct.setText(df.getValueAt(selected, 4).toString());
        
        AddButton.setEnabled(false);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
            txtSupName.setText("");
            txtSupNo.setText("");
            txtEmail.setText("");
            txtSupProduct.setText("");
            txtSupName.requestFocus();
            load();
            AddButton.setEnabled(true);
        
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void txtSupNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupNoKeyPressed
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(Character.isLetter(c)){
           JOptionPane.showMessageDialog(this, "Enter Only Numbers!");
        
        }
    }//GEN-LAST:event_txtSupNoKeyPressed

    private void SearchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String sql="select * from supplier where product=?";
            pst= con.prepareStatement(sql);
            pst.setString(1,txtSearch1.getText());
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                
                txtSupName.setText(rs.getString("name"));
                txtSupNo.setText(rs.getString("phone"));
                txtEmail.setText(rs.getString("email"));
                txtSupProduct.setText(rs.getString("product"));

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_SearchButton1ActionPerformed

    private void txtSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearch1ActionPerformed

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z0-9]+@(.+)$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txtEmail.getText());
        if(!match.matches()){
            elab.setText("*Enter a valid Email");
            txtEmail.setBackground(Color.red);
        
        }
        else{
            elab.setText(null);
            txtEmail.setBackground(Color.white);
        
        }
        
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtSupNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSupNoFocusLost
        // TODO add your handling code here:
        
        String mobileNo=txtSupNo.getText();
        if(mobileNo.matches("^[0-9]*$")&& mobileNo.length()==10)
                {
            plab.setText(null);
            txtSupNo.setBackground(Color.white);
        
        }
        else{
            
            plab.setText("*Enter a valid Phone number");
            txtSupNo.setBackground(Color.red);
        
        }
    }//GEN-LAST:event_txtSupNoFocusLost

    private void ReportButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportButton2ActionPerformed
        // TODO add your handling code here:
         JasperDesign jdesign;
        try {
            jdesign = JRXmlLoader.load("D:\\SLIIT\\YEAR 02\\SEMESTER 02\\PPA\\PROJECT\\KJEnterprises\\src\\main\\java\\Inventory\\Supplierreport1.jrxml");
            String query="select * from supplier";
        
        JRDesignQuery updateQuery=new JRDesignQuery();
        updateQuery.setText(query);
        
        jdesign.setQuery(updateQuery);
        
        JasperReport jreport=JasperCompileManager.compileReport(jdesign);
        JasperPrint jprint=JasperFillManager.fillReport(jreport,null,con);
        
        JasperViewer.viewReport(jprint);
        
        
        } catch (JRException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ReportButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton CloseButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JButton ReportButton2;
    private javax.swing.JButton SearchButton1;
    private javax.swing.JLabel dateTime1;
    private javax.swing.JLabel elab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel plab;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtSearch1;
    private javax.swing.JTextField txtSupName;
    private javax.swing.JTextField txtSupNo;
    private javax.swing.JTextField txtSupProduct;
    // End of variables declaration//GEN-END:variables
}
